### ISSUE TITLE
[12.0][account_chart_update] python lockup in update wizard

### ISSUE THREAD

**Issue by mowny** [OCA/account-financial-tools#912] opened 2019-11-18 19:55 UTC
module: account_chart_update
version: 12.0

Hi, we are just migrating from odoo v10 to v12 Enterprise. In v10, we used l10n_de_skr04_reports, which is supposed to be integrated into the new l10n_de_reports. However, the new tax report comes up almost empty. We were advised to use account_chart_update to restore tax tagging and accounts. The wizard does lock up halfway though.

**Steps to reproduce**
upgrade database to v12
install this module
run the wizard.update.charts.accounts
start with the default options, only Language changed to German

**Current behavior**
logging shows the module proceeds and updates/creates tax accounts until this line:
2019-11-18 19:13:59,834 13421 INFO sourcetronic_live_20161130_o12_v5_migtest odoo.addons.account_chart_update.wizard.wizard_chart_update: Steuer '19% Vorsteuer aus innergem. Erwerb (kein Vorsteuerabzug)' angelegt.
Then the assigned odoo python3 task, according to strace, locks up with:
futex(0x7f3838000e70, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff
and 100% cpu core load until limit_time_real or, having increased that, the nginx timeout strikes.
Modifications are apparently implicitly rolled back once the python3 task dies, the logged changes aren't committed.

**Expected behavior**
Proceed with the updates and eventually come back.

**Comment by pedrobaeza** [comment] 2019-11-18 23:09
Well, this is very weird, because it's processed in a normal Odoo thread, so I doubt it's because module code. Without proper steps to reproduce it, it's barely impossible to hunt the problem. Are you able to reproduce them in OCA runbot?

**Comment by pedrobaeza** [comment] 2020-03-20 09:05
Fixed in e2750be

**Closed as completed by pedrobaeza** 2020-03-20 09:05 UTC
