### ISSUE TITLE
Error message when printing Check Deposit report

### ISSUE THREAD

**Issue by mm82299** [OCA/account-financial-tools#1021] opened 2020-07-07 20:27 UTC
Hello,
We got this error mError:
Odoo Server Error

<details>
```
Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f86da7481e0>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f86e0303048>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1111, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1123, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1369, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1360, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1349, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/odoo11/odoo11-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 640, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 678, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 482, in render_template
    return view_obj.render_template(template, values)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1216, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo11/odoo11-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1225, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise e
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1298_318
  File "<template>", line 3, in body_call_content_317
  File "<template>", line 4, in foreach_316
  File "<decorator-gen-44>", line 2, in compile
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 77, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 292, in compile
    element, document = self.get_template(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 376, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f86da7481e0>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f86e0303048>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1111, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1123, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1369, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1360, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1349, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

load could not load template
Template: report.internal_layout
```
</details>

essage when printing the deposit report:

Would you please help ?
Thanks

**Comment by pedrobaeza** [comment] 2020-07-08 06:52
I'm afraid you have your DB in a bad state, but it's not a problem of the module, so closing this issue. If you try in a fresh DB without third-party modules or in runbot, you'll see that the module works.

**Comment by mm82299** [comment] 2020-07-08 11:13
Dear Pedro,
it seem that this issue is related to the module, i tried in a fresh DB but still got the same error when printing the report:
Error:
Odoo Server Error

<details>
```
Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fcae9663158>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fcaea0726a8>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1125, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1137, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1383, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1374, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1363, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/odoo11/odoo11-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo11/odoo11-server/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 650, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 688, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_actions_report.py", line 482, in render_template
    return view_obj.render_template(template, values)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1230, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/odoo11/odoo11-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1239, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise e
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_843_222
  File "<template>", line 3, in body_call_content_221
  File "<template>", line 4, in foreach_220
  File "<decorator-gen-37>", line 2, in compile
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 77, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 292, in compile
    element, document = self.get_template(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 376, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7fcae9663158>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/odoo11/odoo11-server/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/odoo11/odoo11-server/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fcaea0726a8>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1125, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_ui_view.py", line 1137, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1383, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1374, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/odoo11/odoo11-server/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo11/odoo11-server/odoo/addons/base/ir/ir_model.py", line 1363, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

load could not load template
Template: report.internal_layout
```
</details>

Thanks

**Comment by pedrobaeza** [comment] 2020-07-08 11:26
Is it reproducible on runbot (admin/admin): https://runbot.odoo-community.org/runbot/92/11.0 ?

**Comment by mm82299** [comment] 2020-07-08 12:20
Dear Padro,
thank you for your feedback and patience
I reproduced the same scenario on runbot and still get the same error:
Error:
Odoo Server Error

<details>
```
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f15a361fbf8>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f159d9ae2f0>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1125, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1137, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1383, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1374, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1363, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 1620, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/.repo_requirements/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 1569, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 650, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 688, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_actions_report.py", line 482, in render_template
    return view_obj.render_template(template, values)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1230, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/odoo-11.0/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1239, in render
    return self.env[engine].render(self.id, qcontext)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise e
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_629_1385
  File "<template>", line 3, in body_call_content_1384
  File "<template>", line 4, in foreach_1383
  File "<decorator-gen-37>", line 2, in compile
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 77, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 292, in compile
    element, document = self.get_template(template, options)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 376, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: None
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f15a361fbf8>, 'report.internal_layout', ('en_US', True, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f159d9ae2f0>, 'report.internal_layout')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 372, in get_template
    document = options.get('load', self.load)(template, options)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 85, in load
    template = env['ir.ui.view'].read_template(name)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1125, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1137, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1383, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1374, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/.repo_requirements/odoo/odoo/addons/base/ir/ir_model.py", line 1363, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: report.internal_layout

load could not load template
Template: report.internal_layout
```
</details>

Thanks

**Comment by pedrobaeza** [comment] 2020-07-08 12:24
OK, reopening and I'll check the problem.

**Comment by pedrobaeza** [comment] 2020-07-08 14:34
Sorry, but I have tried in runbot, and I'm not able to reproduce the problem. The only thing is that you need a special check layout to be configured, but nothing more, so re-closing.

**Closed as completed by pedrobaeza** 2020-07-08 14:35 UTC

**Comment by hp-data** [comment] 2023-10-11 22:44
> Sorry, but I have tried in runbot, and I'm not able to reproduce the problem. The only thing is that you need a special check layout to be configured, but nothing more, so re-closing.

I am having this issue, but I am not sure how to configure a special check layout. Our check printing uses the dl103 module
